cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #1c3438
selection_background  #b1cbd1
url_color             #50d7ed

color0   #131313
color1   #ff4584
color2   #50ed5f
color3   #fff245
color4   #2ec8e1
color5   #005e6d
color6   #50d7ed
color7   #e5f6f8
color8   #8a979a
color9   #ff80ab
color10  #88ff94
color11  #fff688
color12  #6feaff
color13  #88eeff
color14  #b2f4ff
color15  #f6fdff
